version: '3'
services:
  db:
    image: db:latest
    container_name: pisspricer-db
    hostname: pisspricer-db
    build: .
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password


