runtime: nodejs14 
instance_class: F2
# env_variables:
#   MYSQL_HOST: ${MYSQL_HOST}
#   MYSQL_USER: ${MYSQL_USER}
#   MYSQL_PASSWORD: ${MYSQL_PASSWORD}
#   MYSQL_DATABASE: ${MYSQL_DATABASE}
#   MYSQL_PORT: ${MYSQL_PORT}
#   IMAGE_BUCKET: ${IMAGE_BUCKET}
#   BUCKET_KEY_PATH: ${BUCKET_KEY_PATH}
#   OPEN_PORT: ${OPEN_PORT}
#   EMAIL_HOST: $EMAIL_HOST
#   EMAIL_USER: $EMAIL_USER
#   EMAIL_PASSWORD: $EMAIL_PASSWORD
#   EMAIL_ADDRESS: $EMAIL_ADDRESS
